
//
//
//Generated by StarUML(tm) Java Add-In
//
//@ Project : Gardener
//@ File Name : BinaryDeltaParser.java
//@ Date : 16/10/2010
//@ Author :
//
//
package br.uff.ic.gardener.patch.delta.parser;

//~--- non-JDK imports --------------------------------------------------------

import br.uff.ic.gardener.patch.chunk.Chunk;
import br.uff.ic.gardener.patch.chunk.action.AddAction;
import br.uff.ic.gardener.patch.chunk.action.DelAction;
import br.uff.ic.gardener.patch.chunk.action.ModAction;
import br.uff.ic.gardener.patch.chunk.action.MovAction;
import br.uff.ic.gardener.patch.chunk.action.NoAction;
import br.uff.ic.gardener.patch.delta.parser.util.Result;
import br.uff.ic.gardener.patch.delta.parser.util.ADeltaParser;
import br.uff.ic.gardener.patch.delta.Delta;

//~--- JDK imports ------------------------------------------------------------

import java.io.FileInputStream;
import java.util.LinkedList;

/**
 *
 * @author Daniel
 */
public class BinaryDeltaParser extends ADeltaParser implements DeltaParser {

    @Override
    public LinkedList<Result> parse(FileInputStream deltas) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     *
     * @param delta
     * @return
     */
    @Override
    protected String headerToString(Delta delta) {
        StringBuilder text = new StringBuilder();

        return text.toString();
    }

    /**
     * Default
     * @param aChunk
     * @return
     */
    @Override
    protected String chunkDataToString(Chunk aChunk) throws Exception {
        StringBuilder text = new StringBuilder();

        text.append(" ");

        return text.toString();
    }

    /**
     *
     * @param action
     * @return
     */
    protected String actionToString(AddAction action) {
        return "";
    }

    /**
     *
     * @param action
     * @return
     */
    protected String actionToString(DelAction action) {
        return "";
    }

    /**
     *
     * @param action
     * @return
     */
    protected String actionToString(ModAction action) {
        return "";
    }

    /**
     *
     * @param action
     * @return
     */
    protected String actionToString(MovAction action) {
        return "";
    }

    /**
     *
     * @param action
     * @return
     */
    protected String actionToString(NoAction action) {
        return "";
    }

}


//~ Formatted by Jindent --- http://www.jindent.com
