
//
//
//Generated by StarUML(tm) Java Add-In
//
//@ Project : Gardener
//@ Info Name : Info.java
//@ Date : 16/10/2010
//@ Author : Daniel
//
//
package br.uff.ic.gardener.patch.delta;

//~--- JDK imports ------------------------------------------------------------

import java.util.Date;

/**
 *
 * @author Daniel
 */
public class Info {
    private int    lenght = -1; //lenght of differences
    private String path   = "";
    private int    start  = -1; //first difference line
    private Date   date;

    /**
     *
     */
    public Info() {}

    /**
     * @return the start
     */
    public int getStart() {
        return start;
    }

    /**
     * @param start the start to set
     */
    public void setStart(int start) {
        this.start = start;
    }

    /**
     * @return the lenght
     */
    public int getLenght() {
        return lenght;
    }

    /**
     * @param lenght the lenght to set
     */
    public void setLenght(int lenght) {
        this.lenght = lenght;
    }

    /**
     * @return the path
     */
    public String getPath() {
        return path;
    }

    /**
     * @param path the path to set
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * @return the date
     */
    public Date getDate() {
        return date;
    }

    /**
     * @param date the date to set
     */
    public void setDate(Date date) {
        this.date = date;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
