
//
//
//Generated by StarUML(tm) Java Add-In
//
//@ Project : Gardener
//@ File Name : DeltaParser.java
//@ Date : 16/10/2010
//@ Author :
//
//
package br.uff.ic.gardener.patch.delta.parser.util;

//~--- non-JDK imports --------------------------------------------------------

import br.uff.ic.gardener.patch.chunk.Chunk;
import br.uff.ic.gardener.patch.chunk.TextChunk;
import br.uff.ic.gardener.patch.chunk.action.Action;

/**
 *
 * @author Daniel
 */
public class ATextDeltaParser extends ADeltaParser {

    /**
     * Default
     * @param aChunk
     * @return
     * @throws Exception
     */
    @Override
    protected String chunkToString(Chunk aChunk) throws Exception {
        if (!(aChunk instanceof TextChunk)) {
            throw new Exception("Unsupported chunk instance");
        }

        return super.chunkToString(aChunk);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
